#! /usr/bin/env php

<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;


require 'vendor/autoload.php';

$app = new Application('Movepedia', '1.0');

$app->register('show')
    ->addArgument('movie', InputArgument::REQUIRED)
    ->setCode(function (InputInterface $input, OutputInterface $output){

        $movie = $input->getArgument('movie');
        $output->writeln('My favourite movie is '. $movie);
    });

$app->run();